/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// deno-lint-ignore-file

// deno-fmt-ignore-file

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SiteImport } from './routes/_site'
import { Route as DashboardRouteImport } from './routes/dashboard/route'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as SiteIndexImport } from './routes/_site/index'
import { Route as DashboardProfileImport } from './routes/dashboard/profile'
import { Route as SiteWaitlistImport } from './routes/_site/waitlist'
import { Route as SiteTermsImport } from './routes/_site/terms'
import { Route as SitePrivacyImport } from './routes/_site/privacy'
import { Route as SitePricingImport } from './routes/_site/pricing'
import { Route as SiteLoginImport } from './routes/_site/login'
import { Route as onboardingOnboardImport } from './routes/(onboarding)/onboard'
import { Route as DashboardFormsIndexImport } from './routes/dashboard/forms/index'
import { Route as DashboardEmailsIndexImport } from './routes/dashboard/emails/index'
import { Route as DashboardFormsCreateImport } from './routes/dashboard/forms/create'
import { Route as DashboardEmailsCreateImport } from './routes/dashboard/emails/create'
import { Route as DashboardFormsFormSlugRouteImport } from './routes/dashboard/forms/$formSlug/route'
import { Route as DashboardFormsFormSlugIndexImport } from './routes/dashboard/forms/$formSlug/index'
import { Route as DashboardFormsFormSlugSettingsImport } from './routes/dashboard/forms/$formSlug/settings'
import { Route as DashboardFormsFormSlugExampleImport } from './routes/dashboard/forms/$formSlug/example'
import { Route as DashboardEmailsVerificationSuccessEmailImport } from './routes/dashboard/emails/verification-success.$email'
import { Route as DashboardFormsFormSlugSubmissionsRouteImport } from './routes/dashboard/forms/$formSlug/submissions/route'
import { Route as DashboardFormsFormSlugSubmissionsIndexImport } from './routes/dashboard/forms/$formSlug/submissions/index'
import { Route as DashboardFormsFormSlugSubmissionsIdImport } from './routes/dashboard/forms/$formSlug/submissions/$id'

// Create/Update Routes

const SiteRoute = SiteImport.update({
  id: '/_site',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRouteRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const SiteIndexRoute = SiteIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)

const DashboardProfileRoute = DashboardProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const SiteWaitlistRoute = SiteWaitlistImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => SiteRoute,
} as any)

const SiteTermsRoute = SiteTermsImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => SiteRoute,
} as any)

const SitePrivacyRoute = SitePrivacyImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SiteRoute,
} as any)

const SitePricingRoute = SitePricingImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => SiteRoute,
} as any)

const SiteLoginRoute = SiteLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SiteRoute,
} as any)

const onboardingOnboardRoute = onboardingOnboardImport.update({
  id: '/(onboarding)/onboard',
  path: '/onboard',
  getParentRoute: () => rootRoute,
} as any)

const DashboardFormsIndexRoute = DashboardFormsIndexImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardEmailsIndexRoute = DashboardEmailsIndexImport.update({
  id: '/emails/',
  path: '/emails/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardFormsCreateRoute = DashboardFormsCreateImport.update({
  id: '/forms/create',
  path: '/forms/create',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardEmailsCreateRoute = DashboardEmailsCreateImport.update({
  id: '/emails/create',
  path: '/emails/create',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardFormsFormSlugRouteRoute =
  DashboardFormsFormSlugRouteImport.update({
    id: '/forms/$formSlug',
    path: '/forms/$formSlug',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

const DashboardFormsFormSlugIndexRoute =
  DashboardFormsFormSlugIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardFormsFormSlugRouteRoute,
  } as any)

const DashboardFormsFormSlugSettingsRoute =
  DashboardFormsFormSlugSettingsImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardFormsFormSlugRouteRoute,
  } as any)

const DashboardFormsFormSlugExampleRoute =
  DashboardFormsFormSlugExampleImport.update({
    id: '/example',
    path: '/example',
    getParentRoute: () => DashboardFormsFormSlugRouteRoute,
  } as any)

const DashboardEmailsVerificationSuccessEmailRoute =
  DashboardEmailsVerificationSuccessEmailImport.update({
    id: '/emails/verification-success/$email',
    path: '/emails/verification-success/$email',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

const DashboardFormsFormSlugSubmissionsRouteRoute =
  DashboardFormsFormSlugSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => DashboardFormsFormSlugRouteRoute,
  } as any)

const DashboardFormsFormSlugSubmissionsIndexRoute =
  DashboardFormsFormSlugSubmissionsIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardFormsFormSlugSubmissionsRouteRoute,
  } as any)

const DashboardFormsFormSlugSubmissionsIdRoute =
  DashboardFormsFormSlugSubmissionsIdImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => DashboardFormsFormSlugSubmissionsRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SiteImport
      parentRoute: typeof rootRoute
    }
    '/(onboarding)/onboard': {
      id: '/(onboarding)/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof onboardingOnboardImport
      parentRoute: typeof rootRoute
    }
    '/_site/login': {
      id: '/_site/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof SiteLoginImport
      parentRoute: typeof SiteImport
    }
    '/_site/pricing': {
      id: '/_site/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof SitePricingImport
      parentRoute: typeof SiteImport
    }
    '/_site/privacy': {
      id: '/_site/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof SitePrivacyImport
      parentRoute: typeof SiteImport
    }
    '/_site/terms': {
      id: '/_site/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof SiteTermsImport
      parentRoute: typeof SiteImport
    }
    '/_site/waitlist': {
      id: '/_site/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof SiteWaitlistImport
      parentRoute: typeof SiteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileImport
      parentRoute: typeof DashboardRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexImport
      parentRoute: typeof SiteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/forms/$formSlug': {
      id: '/dashboard/forms/$formSlug'
      path: '/forms/$formSlug'
      fullPath: '/dashboard/forms/$formSlug'
      preLoaderRoute: typeof DashboardFormsFormSlugRouteImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/emails/create': {
      id: '/dashboard/emails/create'
      path: '/emails/create'
      fullPath: '/dashboard/emails/create'
      preLoaderRoute: typeof DashboardEmailsCreateImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/forms/create': {
      id: '/dashboard/forms/create'
      path: '/forms/create'
      fullPath: '/dashboard/forms/create'
      preLoaderRoute: typeof DashboardFormsCreateImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/emails/': {
      id: '/dashboard/emails/'
      path: '/emails'
      fullPath: '/dashboard/emails'
      preLoaderRoute: typeof DashboardEmailsIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/forms/': {
      id: '/dashboard/forms/'
      path: '/forms'
      fullPath: '/dashboard/forms'
      preLoaderRoute: typeof DashboardFormsIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/forms/$formSlug/submissions': {
      id: '/dashboard/forms/$formSlug/submissions'
      path: '/submissions'
      fullPath: '/dashboard/forms/$formSlug/submissions'
      preLoaderRoute: typeof DashboardFormsFormSlugSubmissionsRouteImport
      parentRoute: typeof DashboardFormsFormSlugRouteImport
    }
    '/dashboard/emails/verification-success/$email': {
      id: '/dashboard/emails/verification-success/$email'
      path: '/emails/verification-success/$email'
      fullPath: '/dashboard/emails/verification-success/$email'
      preLoaderRoute: typeof DashboardEmailsVerificationSuccessEmailImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/forms/$formSlug/example': {
      id: '/dashboard/forms/$formSlug/example'
      path: '/example'
      fullPath: '/dashboard/forms/$formSlug/example'
      preLoaderRoute: typeof DashboardFormsFormSlugExampleImport
      parentRoute: typeof DashboardFormsFormSlugRouteImport
    }
    '/dashboard/forms/$formSlug/settings': {
      id: '/dashboard/forms/$formSlug/settings'
      path: '/settings'
      fullPath: '/dashboard/forms/$formSlug/settings'
      preLoaderRoute: typeof DashboardFormsFormSlugSettingsImport
      parentRoute: typeof DashboardFormsFormSlugRouteImport
    }
    '/dashboard/forms/$formSlug/': {
      id: '/dashboard/forms/$formSlug/'
      path: '/'
      fullPath: '/dashboard/forms/$formSlug/'
      preLoaderRoute: typeof DashboardFormsFormSlugIndexImport
      parentRoute: typeof DashboardFormsFormSlugRouteImport
    }
    '/dashboard/forms/$formSlug/submissions/$id': {
      id: '/dashboard/forms/$formSlug/submissions/$id'
      path: '/$id'
      fullPath: '/dashboard/forms/$formSlug/submissions/$id'
      preLoaderRoute: typeof DashboardFormsFormSlugSubmissionsIdImport
      parentRoute: typeof DashboardFormsFormSlugSubmissionsRouteImport
    }
    '/dashboard/forms/$formSlug/submissions/': {
      id: '/dashboard/forms/$formSlug/submissions/'
      path: '/'
      fullPath: '/dashboard/forms/$formSlug/submissions/'
      preLoaderRoute: typeof DashboardFormsFormSlugSubmissionsIndexImport
      parentRoute: typeof DashboardFormsFormSlugSubmissionsRouteImport
    }
  }
}

// Create and export the route tree

interface DashboardFormsFormSlugSubmissionsRouteRouteChildren {
  DashboardFormsFormSlugSubmissionsIdRoute: typeof DashboardFormsFormSlugSubmissionsIdRoute
  DashboardFormsFormSlugSubmissionsIndexRoute: typeof DashboardFormsFormSlugSubmissionsIndexRoute
}

const DashboardFormsFormSlugSubmissionsRouteRouteChildren: DashboardFormsFormSlugSubmissionsRouteRouteChildren =
  {
    DashboardFormsFormSlugSubmissionsIdRoute:
      DashboardFormsFormSlugSubmissionsIdRoute,
    DashboardFormsFormSlugSubmissionsIndexRoute:
      DashboardFormsFormSlugSubmissionsIndexRoute,
  }

const DashboardFormsFormSlugSubmissionsRouteRouteWithChildren =
  DashboardFormsFormSlugSubmissionsRouteRoute._addFileChildren(
    DashboardFormsFormSlugSubmissionsRouteRouteChildren,
  )

interface DashboardFormsFormSlugRouteRouteChildren {
  DashboardFormsFormSlugSubmissionsRouteRoute: typeof DashboardFormsFormSlugSubmissionsRouteRouteWithChildren
  DashboardFormsFormSlugExampleRoute: typeof DashboardFormsFormSlugExampleRoute
  DashboardFormsFormSlugSettingsRoute: typeof DashboardFormsFormSlugSettingsRoute
  DashboardFormsFormSlugIndexRoute: typeof DashboardFormsFormSlugIndexRoute
}

const DashboardFormsFormSlugRouteRouteChildren: DashboardFormsFormSlugRouteRouteChildren =
  {
    DashboardFormsFormSlugSubmissionsRouteRoute:
      DashboardFormsFormSlugSubmissionsRouteRouteWithChildren,
    DashboardFormsFormSlugExampleRoute: DashboardFormsFormSlugExampleRoute,
    DashboardFormsFormSlugSettingsRoute: DashboardFormsFormSlugSettingsRoute,
    DashboardFormsFormSlugIndexRoute: DashboardFormsFormSlugIndexRoute,
  }

const DashboardFormsFormSlugRouteRouteWithChildren =
  DashboardFormsFormSlugRouteRoute._addFileChildren(
    DashboardFormsFormSlugRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardFormsFormSlugRouteRoute: typeof DashboardFormsFormSlugRouteRouteWithChildren
  DashboardEmailsCreateRoute: typeof DashboardEmailsCreateRoute
  DashboardFormsCreateRoute: typeof DashboardFormsCreateRoute
  DashboardEmailsIndexRoute: typeof DashboardEmailsIndexRoute
  DashboardFormsIndexRoute: typeof DashboardFormsIndexRoute
  DashboardEmailsVerificationSuccessEmailRoute: typeof DashboardEmailsVerificationSuccessEmailRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardFormsFormSlugRouteRoute:
    DashboardFormsFormSlugRouteRouteWithChildren,
  DashboardEmailsCreateRoute: DashboardEmailsCreateRoute,
  DashboardFormsCreateRoute: DashboardFormsCreateRoute,
  DashboardEmailsIndexRoute: DashboardEmailsIndexRoute,
  DashboardFormsIndexRoute: DashboardFormsIndexRoute,
  DashboardEmailsVerificationSuccessEmailRoute:
    DashboardEmailsVerificationSuccessEmailRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface SiteRouteChildren {
  SiteLoginRoute: typeof SiteLoginRoute
  SitePricingRoute: typeof SitePricingRoute
  SitePrivacyRoute: typeof SitePrivacyRoute
  SiteTermsRoute: typeof SiteTermsRoute
  SiteWaitlistRoute: typeof SiteWaitlistRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteLoginRoute: SiteLoginRoute,
  SitePricingRoute: SitePricingRoute,
  SitePrivacyRoute: SitePrivacyRoute,
  SiteTermsRoute: SiteTermsRoute,
  SiteWaitlistRoute: SiteWaitlistRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '': typeof SiteRouteWithChildren
  '/onboard': typeof onboardingOnboardRoute
  '/login': typeof SiteLoginRoute
  '/pricing': typeof SitePricingRoute
  '/privacy': typeof SitePrivacyRoute
  '/terms': typeof SiteTermsRoute
  '/waitlist': typeof SiteWaitlistRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/': typeof SiteIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/forms/$formSlug': typeof DashboardFormsFormSlugRouteRouteWithChildren
  '/dashboard/emails/create': typeof DashboardEmailsCreateRoute
  '/dashboard/forms/create': typeof DashboardFormsCreateRoute
  '/dashboard/emails': typeof DashboardEmailsIndexRoute
  '/dashboard/forms': typeof DashboardFormsIndexRoute
  '/dashboard/forms/$formSlug/submissions': typeof DashboardFormsFormSlugSubmissionsRouteRouteWithChildren
  '/dashboard/emails/verification-success/$email': typeof DashboardEmailsVerificationSuccessEmailRoute
  '/dashboard/forms/$formSlug/example': typeof DashboardFormsFormSlugExampleRoute
  '/dashboard/forms/$formSlug/settings': typeof DashboardFormsFormSlugSettingsRoute
  '/dashboard/forms/$formSlug/': typeof DashboardFormsFormSlugIndexRoute
  '/dashboard/forms/$formSlug/submissions/$id': typeof DashboardFormsFormSlugSubmissionsIdRoute
  '/dashboard/forms/$formSlug/submissions/': typeof DashboardFormsFormSlugSubmissionsIndexRoute
}

export interface FileRoutesByTo {
  '/onboard': typeof onboardingOnboardRoute
  '/login': typeof SiteLoginRoute
  '/pricing': typeof SitePricingRoute
  '/privacy': typeof SitePrivacyRoute
  '/terms': typeof SiteTermsRoute
  '/waitlist': typeof SiteWaitlistRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/': typeof SiteIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/emails/create': typeof DashboardEmailsCreateRoute
  '/dashboard/forms/create': typeof DashboardFormsCreateRoute
  '/dashboard/emails': typeof DashboardEmailsIndexRoute
  '/dashboard/forms': typeof DashboardFormsIndexRoute
  '/dashboard/emails/verification-success/$email': typeof DashboardEmailsVerificationSuccessEmailRoute
  '/dashboard/forms/$formSlug/example': typeof DashboardFormsFormSlugExampleRoute
  '/dashboard/forms/$formSlug/settings': typeof DashboardFormsFormSlugSettingsRoute
  '/dashboard/forms/$formSlug': typeof DashboardFormsFormSlugIndexRoute
  '/dashboard/forms/$formSlug/submissions/$id': typeof DashboardFormsFormSlugSubmissionsIdRoute
  '/dashboard/forms/$formSlug/submissions': typeof DashboardFormsFormSlugSubmissionsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/(onboarding)/onboard': typeof onboardingOnboardRoute
  '/_site/login': typeof SiteLoginRoute
  '/_site/pricing': typeof SitePricingRoute
  '/_site/privacy': typeof SitePrivacyRoute
  '/_site/terms': typeof SiteTermsRoute
  '/_site/waitlist': typeof SiteWaitlistRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/_site/': typeof SiteIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/forms/$formSlug': typeof DashboardFormsFormSlugRouteRouteWithChildren
  '/dashboard/emails/create': typeof DashboardEmailsCreateRoute
  '/dashboard/forms/create': typeof DashboardFormsCreateRoute
  '/dashboard/emails/': typeof DashboardEmailsIndexRoute
  '/dashboard/forms/': typeof DashboardFormsIndexRoute
  '/dashboard/forms/$formSlug/submissions': typeof DashboardFormsFormSlugSubmissionsRouteRouteWithChildren
  '/dashboard/emails/verification-success/$email': typeof DashboardEmailsVerificationSuccessEmailRoute
  '/dashboard/forms/$formSlug/example': typeof DashboardFormsFormSlugExampleRoute
  '/dashboard/forms/$formSlug/settings': typeof DashboardFormsFormSlugSettingsRoute
  '/dashboard/forms/$formSlug/': typeof DashboardFormsFormSlugIndexRoute
  '/dashboard/forms/$formSlug/submissions/$id': typeof DashboardFormsFormSlugSubmissionsIdRoute
  '/dashboard/forms/$formSlug/submissions/': typeof DashboardFormsFormSlugSubmissionsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | ''
    | '/onboard'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/waitlist'
    | '/dashboard/profile'
    | '/'
    | '/dashboard/'
    | '/dashboard/forms/$formSlug'
    | '/dashboard/emails/create'
    | '/dashboard/forms/create'
    | '/dashboard/emails'
    | '/dashboard/forms'
    | '/dashboard/forms/$formSlug/submissions'
    | '/dashboard/emails/verification-success/$email'
    | '/dashboard/forms/$formSlug/example'
    | '/dashboard/forms/$formSlug/settings'
    | '/dashboard/forms/$formSlug/'
    | '/dashboard/forms/$formSlug/submissions/$id'
    | '/dashboard/forms/$formSlug/submissions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/onboard'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/waitlist'
    | '/dashboard/profile'
    | '/'
    | '/dashboard'
    | '/dashboard/emails/create'
    | '/dashboard/forms/create'
    | '/dashboard/emails'
    | '/dashboard/forms'
    | '/dashboard/emails/verification-success/$email'
    | '/dashboard/forms/$formSlug/example'
    | '/dashboard/forms/$formSlug/settings'
    | '/dashboard/forms/$formSlug'
    | '/dashboard/forms/$formSlug/submissions/$id'
    | '/dashboard/forms/$formSlug/submissions'
  id:
    | '__root__'
    | '/dashboard'
    | '/_site'
    | '/(onboarding)/onboard'
    | '/_site/login'
    | '/_site/pricing'
    | '/_site/privacy'
    | '/_site/terms'
    | '/_site/waitlist'
    | '/dashboard/profile'
    | '/_site/'
    | '/dashboard/'
    | '/dashboard/forms/$formSlug'
    | '/dashboard/emails/create'
    | '/dashboard/forms/create'
    | '/dashboard/emails/'
    | '/dashboard/forms/'
    | '/dashboard/forms/$formSlug/submissions'
    | '/dashboard/emails/verification-success/$email'
    | '/dashboard/forms/$formSlug/example'
    | '/dashboard/forms/$formSlug/settings'
    | '/dashboard/forms/$formSlug/'
    | '/dashboard/forms/$formSlug/submissions/$id'
    | '/dashboard/forms/$formSlug/submissions/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
  onboardingOnboardRoute: typeof onboardingOnboardRoute
}

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
  onboardingOnboardRoute: onboardingOnboardRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/dashboard",
        "/_site",
        "/(onboarding)/onboard"
      ]
    },
    "/dashboard": {
      "filePath": "dashboard/route.tsx",
      "children": [
        "/dashboard/profile",
        "/dashboard/",
        "/dashboard/forms/$formSlug",
        "/dashboard/emails/create",
        "/dashboard/forms/create",
        "/dashboard/emails/",
        "/dashboard/forms/",
        "/dashboard/emails/verification-success/$email"
      ]
    },
    "/_site": {
      "filePath": "_site.tsx",
      "children": [
        "/_site/login",
        "/_site/pricing",
        "/_site/privacy",
        "/_site/terms",
        "/_site/waitlist",
        "/_site/"
      ]
    },
    "/(onboarding)/onboard": {
      "filePath": "(onboarding)/onboard.tsx"
    },
    "/_site/login": {
      "filePath": "_site/login.tsx",
      "parent": "/_site"
    },
    "/_site/pricing": {
      "filePath": "_site/pricing.tsx",
      "parent": "/_site"
    },
    "/_site/privacy": {
      "filePath": "_site/privacy.tsx",
      "parent": "/_site"
    },
    "/_site/terms": {
      "filePath": "_site/terms.tsx",
      "parent": "/_site"
    },
    "/_site/waitlist": {
      "filePath": "_site/waitlist.tsx",
      "parent": "/_site"
    },
    "/dashboard/profile": {
      "filePath": "dashboard/profile.tsx",
      "parent": "/dashboard"
    },
    "/_site/": {
      "filePath": "_site/index.tsx",
      "parent": "/_site"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/forms/$formSlug": {
      "filePath": "dashboard/forms/$formSlug/route.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/forms/$formSlug/submissions",
        "/dashboard/forms/$formSlug/example",
        "/dashboard/forms/$formSlug/settings",
        "/dashboard/forms/$formSlug/"
      ]
    },
    "/dashboard/emails/create": {
      "filePath": "dashboard/emails/create.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/forms/create": {
      "filePath": "dashboard/forms/create.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/emails/": {
      "filePath": "dashboard/emails/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/forms/": {
      "filePath": "dashboard/forms/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/forms/$formSlug/submissions": {
      "filePath": "dashboard/forms/$formSlug/submissions/route.tsx",
      "parent": "/dashboard/forms/$formSlug",
      "children": [
        "/dashboard/forms/$formSlug/submissions/$id",
        "/dashboard/forms/$formSlug/submissions/"
      ]
    },
    "/dashboard/emails/verification-success/$email": {
      "filePath": "dashboard/emails/verification-success.$email.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/forms/$formSlug/example": {
      "filePath": "dashboard/forms/$formSlug/example.tsx",
      "parent": "/dashboard/forms/$formSlug"
    },
    "/dashboard/forms/$formSlug/settings": {
      "filePath": "dashboard/forms/$formSlug/settings.tsx",
      "parent": "/dashboard/forms/$formSlug"
    },
    "/dashboard/forms/$formSlug/": {
      "filePath": "dashboard/forms/$formSlug/index.tsx",
      "parent": "/dashboard/forms/$formSlug"
    },
    "/dashboard/forms/$formSlug/submissions/$id": {
      "filePath": "dashboard/forms/$formSlug/submissions/$id.tsx",
      "parent": "/dashboard/forms/$formSlug/submissions"
    },
    "/dashboard/forms/$formSlug/submissions/": {
      "filePath": "dashboard/forms/$formSlug/submissions/index.tsx",
      "parent": "/dashboard/forms/$formSlug/submissions"
    }
  }
}
ROUTE_MANIFEST_END */
